### ISSUE TITLE
Chapter 4 code listing

### ISSUE THREAD

**Issue by Opioid** [Apress/Ray-Tracing-Gems-II#3]
Listing 4-1, is:

`vec3 tmpu = P - A, tmpv = P - B, tmpw = P - C`
`// ...`
`vec3 Pp = P + u*tmpu + v*tmpv + w*tmpw`

As source [Spectral light transport simulation using a precision-based ray tracing architecture](https://oparu.uni-ulm.de/xmlui/handle/123456789/3930) is quoted. Here, the last line looks like this (adjusting for code style):

`vec3 Pp = u*(A + tmpu) + v*(B + tmpv) + w*(C + tmpw)`

I don´t think they are equivalent, and the first version gives me unexpected results. Is this a mistake?

**Comment by acmarrs-nvidia** [comment]
Hi @Opioid - thanks for your message! I've pointed the author of Chapter 4 to this post. They'll review and either respond here directly or I'll post for them after they've had a chance to review.

**Comment by hanatos** [comment]
heya, thanks for your message (and sorry for the wait, was on leave). after double checking the code listings i still think they are equivalent:
```
    Pp = u*(A + tmpu) + v*(B + tmpv) + w*(C + tmpw)
<=> Pp = u*A + u*tmpu + v*B + v*tmpv + w*C + w*tmpw
<=> Pp = u*A + v*B + w*C    + u*tmpu + v*tmpv + w*tmpw
<=> Pp = P                  + u*tmpu + v*tmpv + w*tmpw
```
which will also result in `Pp == P` in the trivial case with flat triangles, as a sanity check (because then the gram-schmidt step in the `// ...` part of your listing disappears and thus `Pp = P + (u+v+w)*P - u*A - v*B - w*C = 2P - P = P`).

does that make any sense to you? in my implementation i also used the second version `vec3 Pp = u*(A + tmpu) + v*(B + tmpv) + w*(C + tmpw)`, so from that side it'd be entirely possible that the reformulation step would be flawed. at this point i'd probably assume some bug maybe permuting the barycentrics uvw?

**Comment by Opioid** [comment]
> at this point i'd probably assume some bug maybe permuting the barycentrics uvw?

Yes, I think you are spot on! I took another look and I think my barycentric coordinates are ordered (w, u, v) compared to what is expected here. After adjusting for this, I get the same results with both formulas. Thanks for the hint!
